### PR TITLE
feat: add support for django 3.2

### PR DESCRIPTION
**Pull request by mariajgrimaldi**
**Description**
This PR adds support for Django 3.2 tests

### CODE REVIEW

**Comment by mariajgrimaldi** [comment]
Hi there @pmitros, I followed your suggestion [here](https://github.com/pmitros/FeedbackXBlock/issues/8#issuecomment-936721431) :)

Can you approve running the workflow? Thanks in advance!

**Comment by pmitros** [comment]
Thank you for your contribution.

**Comment by pmitros** [comment]
@mariajgrimaldi Actually, looking at this, it looks like the workflow reported errors. Can you please look into it and if there's an issue, submit another PR or add to this one? I have zero capacity right now beyond a quick glance + merge.

**Comment by mariajgrimaldi** [comment]
I'm on it, @pmitros: #10, but my workflows keep getting canceled, and it seems I can't rerun them

**Comment by pmitros** [comment]
I can rerun them. I see the same cancellations. Looking at the jobs, most seem to complete successfully. Go to https://github.com/pmitros/FeedbackXBlock/pull/10/checks?check_run_id=3894967850 and click around. 

2.7 fails. Is 2.7 still being used? Python 2 is EOLed. Perhaps older Python/Django versions might be removed, if no longer supported.

**Pull request merged**
